[package]
name = "towerdef"
version = "0.1.0"
authors = ["Jazarro <nospam.git@boschman.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.0"
log = { version = "0.4.6", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
derive-new = "0.5"
specs-derive = "0.4"
precompile = { path = "precompile" }
amethyst = {version = "0.15.0", features = ["vulkan"]}